import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'node:path';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text-summary', 'json-summary', 'html'],
      reportsDirectory: './coverage',
      // Measure the whole of src, not just files a test happened to import —
      // otherwise an untested module vanishes from the denominator and the
      // percentage flatters itself. In vitest 4 that is what `include` already
      // does; the v3 `all: true` flag was removed and is a type error here.
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        // Every exclusion below is either generated, a type-only declaration,
        // or test scaffolding. No business logic is excluded.
        'src/**/*.{test,spec}.{ts,tsx}',
        'src/**/__tests__/**',
        'src/test/**', // vitest scaffolding (server-only stub)
        'src/lib/supabase/types.ts', // generated by the Supabase CLI
        'src/types/**', // type declarations, no runtime
        'src/app/**/{layout,loading,error,not-found}.tsx', // framework shells
      ],
      // Ratchet, not aspiration. The global figures are the MEASURED baseline
      // (2026-08-02: lines 17.10, statements 16.61, branches 11.08, functions
      // 14.27) minus a point of slack, so the gate fails on a REGRESSION
      // instead of failing every commit until some future cleanup. Raise them
      // as coverage climbs; never lower one to make a build pass.
      //
      // The global number is low because `all: true` counts the entire UI,
      // most of which has no tests — app/(app) alone is 313/3036 lines. That
      // is the honest picture, and averaging it away would hide the one thing
      // worth protecting: the money path is covered, and these per-file gates
      // are what actually stop it regressing. Each is set just under its
      // current value.
      thresholds: {
        // Ratcheted 2026-08-02 after covering lib/billing (was 16/15/10/13):
        // lines 17.50, statements 17.08, branches 11.49, functions 14.83.
        lines: 17,
        statements: 16,
        branches: 11,
        functions: 14,

        // Measured per metric — line % is NOT a stand-in for statement or
        // function %, which is how a first pass at these numbers failed.
        // credits.ts functions is 75% (3/4) because formatCredits is a pure UI
        // helper with no test; that is the honest figure, not 100.
        // Both were 0% until 2026-08-02. plans.ts decides what a customer
        // receives for their money, so it is held at 100.
        'src/lib/billing/plans.ts': { lines: 100, statements: 100, branches: 90, functions: 100 },
        'src/lib/billing/stripe.ts': {
          lines: 100,
          statements: 100,
          branches: 100,
          functions: 100,
        },
        'src/lib/credits.ts': { lines: 95, statements: 95, branches: 100, functions: 74 },
        'src/lib/publish-safety.ts': { lines: 99, statements: 99, branches: 67, functions: 99 },
        'src/lib/zernio-webhooks.ts': { lines: 93, statements: 85, branches: 55, functions: 99 },
        'src/app/api/stripe/webhook/route.ts': {
          lines: 60,
          statements: 57,
          branches: 51,
          functions: 80,
        },
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      // 'server-only' is a Next.js boundary marker that throws outside RSC.
      // Stub it in tests so we can unit-test functions that live in
      // server-only modules (e.g. prompt builders).
      'server-only': path.resolve(__dirname, './src/test/server-only-stub.ts'),
    },
  },
});
