-- =============================================================================
-- 0015_creative_agent_runs.sql
-- =============================================================================
-- Persists Creative Agents orchestration output:
--   - one run per prompt
--   - normalized production assets generated by each agent
--   - review issues that can be fixed and handed off to Storyboard
-- =============================================================================

create table if not exists public.creative_agent_runs (
  id                 uuid        primary key default gen_random_uuid(),
  workspace_id       uuid        not null references public.workspaces(id) on delete cascade,
  storyboard_id      uuid        references public.storyboards(id) on delete set null,
  prompt             text        not null,
  campaign_title     text        not null,
  concept_line       text        not null,
  brand_defaults     jsonb       not null default '{}'::jsonb,
  agent_status       text        not null default 'saved'
                                   check (agent_status in ('saved', 'sent_to_storyboard')),
  asset_count        integer     not null default 0 check (asset_count >= 0),
  fixed_issue_count  integer     not null default 0 check (fixed_issue_count >= 0),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create unique index if not exists creative_agent_runs_id_workspace_id_key
  on public.creative_agent_runs(id, workspace_id);

create table if not exists public.creative_agent_assets (
  id            uuid        primary key default gen_random_uuid(),
  run_id        uuid        not null,
  workspace_id  uuid        not null references public.workspaces(id) on delete cascade,
  kind          text        not null
                            check (kind in (
                              'concept',
                              'script',
                              'voiceover',
                              'music',
                              'sound_design',
                              'brand_identity',
                              'shot',
                              'compose_note'
                            )),
  title         text        not null,
  body          text        not null,
  metadata      jsonb       not null default '{}'::jsonb,
  position      integer     not null default 0 check (position >= 0),
  created_at    timestamptz not null default now(),
  foreign key (run_id, workspace_id)
    references public.creative_agent_runs(id, workspace_id)
    on delete cascade
);

create table if not exists public.creative_agent_review_issues (
  id            uuid        primary key default gen_random_uuid(),
  run_id        uuid        not null,
  workspace_id  uuid        not null references public.workspaces(id) on delete cascade,
  external_id   text        not null,
  asset_label   text        not null,
  severity      text        not null check (severity in ('fixing', 'clear')),
  label         text        not null,
  before        text        not null,
  fix           text        not null,
  status        text        not null default 'open' check (status in ('open', 'fixed', 'clear')),
  fixed_at      timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (run_id, external_id),
  foreign key (run_id, workspace_id)
    references public.creative_agent_runs(id, workspace_id)
    on delete cascade
);

create index if not exists creative_agent_runs_workspace_id_idx
  on public.creative_agent_runs(workspace_id, created_at desc);

create index if not exists creative_agent_assets_run_id_idx
  on public.creative_agent_assets(run_id, position);

create index if not exists creative_agent_assets_workspace_id_idx
  on public.creative_agent_assets(workspace_id);

create index if not exists creative_agent_review_issues_run_id_idx
  on public.creative_agent_review_issues(run_id, status);

create index if not exists creative_agent_review_issues_workspace_id_idx
  on public.creative_agent_review_issues(workspace_id);

drop trigger if exists creative_agent_runs_set_updated_at on public.creative_agent_runs;
create trigger creative_agent_runs_set_updated_at
  before update on public.creative_agent_runs
  for each row execute function public.set_updated_at();

drop trigger if exists creative_agent_review_issues_set_updated_at
  on public.creative_agent_review_issues;
create trigger creative_agent_review_issues_set_updated_at
  before update on public.creative_agent_review_issues
  for each row execute function public.set_updated_at();

alter table public.creative_agent_runs enable row level security;
alter table public.creative_agent_assets enable row level security;
alter table public.creative_agent_review_issues enable row level security;

grant select, insert, update, delete on public.creative_agent_runs to authenticated;
grant select, insert, update, delete on public.creative_agent_assets to authenticated;
grant select, insert, update, delete on public.creative_agent_review_issues to authenticated;

drop policy if exists "owners can read creative agent runs" on public.creative_agent_runs;
drop policy if exists "owners can insert creative agent runs" on public.creative_agent_runs;
drop policy if exists "owners can update creative agent runs" on public.creative_agent_runs;
drop policy if exists "owners can delete creative agent runs" on public.creative_agent_runs;

create policy "owners can read creative agent runs"
  on public.creative_agent_runs for select
  using (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

create policy "owners can insert creative agent runs"
  on public.creative_agent_runs for insert
  with check (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

create policy "owners can update creative agent runs"
  on public.creative_agent_runs for update
  using (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

create policy "owners can delete creative agent runs"
  on public.creative_agent_runs for delete
  using (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

drop policy if exists "owners can read creative agent assets" on public.creative_agent_assets;
drop policy if exists "owners can insert creative agent assets" on public.creative_agent_assets;
drop policy if exists "owners can update creative agent assets" on public.creative_agent_assets;
drop policy if exists "owners can delete creative agent assets" on public.creative_agent_assets;

create policy "owners can read creative agent assets"
  on public.creative_agent_assets for select
  using (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

create policy "owners can insert creative agent assets"
  on public.creative_agent_assets for insert
  with check (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

create policy "owners can update creative agent assets"
  on public.creative_agent_assets for update
  using (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

create policy "owners can delete creative agent assets"
  on public.creative_agent_assets for delete
  using (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

drop policy if exists "owners can read creative agent issues" on public.creative_agent_review_issues;
drop policy if exists "owners can insert creative agent issues" on public.creative_agent_review_issues;
drop policy if exists "owners can update creative agent issues" on public.creative_agent_review_issues;
drop policy if exists "owners can delete creative agent issues" on public.creative_agent_review_issues;

create policy "owners can read creative agent issues"
  on public.creative_agent_review_issues for select
  using (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

create policy "owners can insert creative agent issues"
  on public.creative_agent_review_issues for insert
  with check (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

create policy "owners can update creative agent issues"
  on public.creative_agent_review_issues for update
  using (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));

create policy "owners can delete creative agent issues"
  on public.creative_agent_review_issues for delete
  using (workspace_id in (select id from public.workspaces where owner_user_id = (select auth.uid())));
